### ISSUE TITLE
Notification issue

### ISSUE THREAD

**Issue by bjoernr-de** [tobijanssen/GSOPlan#21]
Guess you're not using github anymore (latest commit 10 month ago), anyway there's a major problem with notifications. 
Got spammed tomorrow morning after clicking "Jetzt aktualisieren".
Also did you change something on the background service? Seems not to be running as it should. I'm not getting any updates unless I click "Jetzt aktualisieren" in the app itself.

Hardware/Software:
- Samsung Galaxy S3 (GT-I9300)
- Stock Android 4.3
- GSOPlan Version 1.08Beta

![2014-05-07 04 13 43](https://cloud.githubusercontent.com/assets/2854699/2898491/4d3de256-d59f-11e3-986e-2d383b61fd08.png)

**Comment by tobijanssen** [comment]
Thanks for your Bug report! 
The spamming notification issue is already on my todo list for the next major update. 

The issue of the not running background service is quite new. With a bit of luck, its just not activated in your application settings? Its called "Hintergrunddaten".
If you have this setting checked, your log file tells us some more information. Go to "Einstellungen" -> "Über GSOPlan" -> down to the bottom: "Log Datei exportieren". You can send it for example to your Dropbox, or email it directly to my email address(its pre-selectet, if you choose your prefered email app)

**Comment by tobijanssen** [comment]
Oh, and thats right I'm not using github anymore. GSOPlan has moved to http://sourceforge.net/p/gsoplan

**Comment by bjoernr-de** [comment]
No problem, glad do help.

And yeah, my bad - "Hintergrunddaten" were turned off.
So should be working now - Thanks ;-)

## 

I'll close that issue after the bug is already known and listed on sourceforge.
